<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="
             http://maven.apache.org/POM/4.0.0
             https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.votri</groupId>
    <artifactId>CombatKeepInventory</artifactId>
    <version>1.1.0-SNAPSHOT</version>

    <packaging>pom</packaging>

    <name>CombatKeepInventory</name>
    <description>Combat based inventory protection plugin</description>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

        <maven.compiler.release>25</maven.compiler.release>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>

        <maven.compiler.version>3.14.0</maven.compiler.version>
        <maven.resources.version>3.3.1</maven.resources.version>
        <maven.jar.version>3.4.2</maven.jar.version>

        <!--
            IMPORTANT:
            Paper 26.1+ does NOT use:
            26.1.2-R0.1-SNAPSHOT

            It uses the new build-based version format.
        -->
        <paper.api.version>26.1.build.74-stable</paper.api.version>

        <velocity.api.version>3.4.0-SNAPSHOT>

    </properties>

    <modules>
        <module>cki-core</module>
        <module>cki-bukkit</module>
        <module>cki-velocity</module>
    </modules>

    <repositories>

        <!-- Paper -->
        <repository>
            <id>papermc</id>
            <url>https://repo.papermc.io/repository/maven-public/</url>
        </repository>

        <!-- Velocity -->
        <repository>
            <id>velocity</id>
            <url>https://repo.velocitypowered.com/snapshots/</url>
        </repository>

        <!-- Maven Central -->
        <repository>
            <id>central</id>
            <url>https://repo.maven.apache.org/maven2/</url>
        </repository>

    </repositories>

    <build>

        <pluginManagement>
            <plugins>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven.compiler.version}</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-resources-plugin</artifactId>
                    <version>${maven.resources.version}</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>${maven.jar.version}</version>
                </plugin>

            </plugins>
        </pluginManagement>

    </build>

</project>