name: CombatKeepInventory
version: 1.1.0-SNAPSHOT-build2
main: com.votri.combatkeepinv.CombatKeepInventory
api-version: '1.21'

author: ThanhNhan-thanhnhan0928_VoTriMC
description: Advanced combat and inventory death management plugin.

softdepend:
  - WorldGuard

commands:

  cki:
    description: CombatKeepInventory main command
    usage: /cki <reload|info|pvp>
    aliases:
      - combatkeepinventory

permissions:

  combatkeepinventory.admin:
    description: Allows administrative CombatKeepInventory commands
    default: op

  combatkeepinventory.bypass:
    description: Prevents CombatKeepInventory from affecting the player
    default: false

  combatkeepinventory.pvp:
    description: Allows the player to toggle global PvP
    default: op